[package]
name = "sentiric-sip-gateway-service"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
# YENİ: dotenv'in daha modern versiyonu olan dotenvy'yi kullanıyoruz.
dotenvy = "0.15"
# YENİ: Daha iyi hata yönetimi için anyhow ekliyoruz.
anyhow = "1.0"