# docker-compose.prod.yml
# Service Üretim ortamı

networks:
  sentiric-net:
    name: "${NETWORK_NAME:-sentiric-net}"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

services:
  # [capability-telephony]: Yetenek Servisleri (Capability Layer)
  # --------------------------------------------------  

  # sadece geçit olarak kullanılacak ise
  sip-gateway:
    image: ghcr.io/sentiric/sentiric-sip-gateway-service:${TAG:-latest}
    env_file: ["${ENV_FILE_PATH}"]
    volumes: 
      - "${CONFIG_REPO_PATH}:/sentiric-config:ro"     
    ports: 
      - "{SIP_GATEWAY_UDP_PORT:-13014}:${SIP_GATEWAY_UDP_PORT:-13014}/udp"
    networks:
      sentiric-net:
        ipv4_address: ${SIP_GATEWAY_IPV4_ADDRESS}       
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pgrep -f sentiric-sip-gateway-service || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s    
    # depends_on:
    #   sip-signaling: { condition: service_healthy }