networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

services:
  sip-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: sentiric-sip-gateway-service
  
    env_file: 
      - ./.env 

    environment:
      - SIP_GATEWAY_LISTEN_PORT=8060
    ports: ["${SIP_GATEWAY_SERVICE_PORT:-5060}:8060/udp"]  
    # ports: ["${SIP_GATEWAY_SERVICE_PORT:-5060}:${SIP_GATEWAY_LISTEN_PORT:-8060}/udp"]

    networks:
      - sentiric-net

    profiles:
      - default
      - telekom

    restart: always
    
    mem_limit: 128m
    cpus: 0.2