networks:
  sentiric-net:
    name: ${NETWORK_NAME:-sentiric-net}
    driver: bridge

services:
  sip-gateway:

    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE_NAME: sentiric-sip-gateway
  
    env_file: 
      - ./.env

    # volumes:
    #   - ../sentiric-config/tls/certs:/etc/sentiric/tls:ro      

    ports:
      - "5060:${SIP_GATEWAY_SERVICE_PORT}/udp"

    networks:
      - sentiric-net

    profiles:
      - default
      - telekom

    restart: always
    
    mem_limit: 128m
    cpus: 0.2    