# docker-compose.yml
# Service Üretim ortamı

networks:
  sentiric-net:
    name: "${NETWORK_NAME:-sentiric-net}"
    driver: bridge
    ipam:
      config:
        - subnet: ${NETWORK_SUBNET}
          gateway: ${NETWORK_GATEWAY}

services:
  # [capability-telephony]: Yetenek Servisleri (Capability Layer)
  # --------------------------------------------------  

  # sadece geçit olarak kullanılacak ise
  sip-gateway:
    image: ghcr.io/sentiric/sentiric-sip-gateway-service:${TAG:-latest}
    env_file: ["${ENV_FILE_PATH}"]
    ports: 
      - "5060:${SIP_GATEWAY_UDP_PORT:-13014}/udp"
    networks:
      sentiric-net:
        ipv4_address: ${SIP_GATEWAY_IPV4_ADDRESS}       
    restart: always
    # depends_on: {
    #   sip-signaling: { condition: service_started }
    # }  